### ISSUE TITLE
Transfer extension to Slicer organization

### ISSUE THREAD

**Issue by jcfr** [Slicer/SlicerDeveloperToolsForExtensions#15]
Hi @fbudin69500 , 

To stream the maintenance, would you consider transferring the ownership to Slicer GitHub organization ? 

That said, if you still plan to be active and help with the development, we can keep the code here.

Let us know what you think, 

Cc: @sjh26

**Comment by fbudin69500** [comment]
@jcfr Ownership transferred.

**Comment by jcfr** [comment]
Thanks @fbudin69500
